/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sun Apr 15 19:26:58 2018. */

#include "TemperatureProtocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t BaseMessage_fields[8] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, BaseMessage, type, type, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, BaseMessage, authRequest, type, &AuthRequest_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, BaseMessage, authResponse, authRequest, &AuthResponse_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, BaseMessage, notifyRequest, authResponse, &NotifyRequest_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, BaseMessage, configSet, notifyRequest, &ConfigSet_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, BaseMessage, configChanges, configSet, &ConfigChanges_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, BaseMessage, actualConfig, configChanges, &ActualConfig_fields),
    PB_LAST_FIELD
};

const pb_field_t AuthRequest_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AuthRequest, type, type, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, AuthRequest, version, type, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, AuthRequest, apiKey, version, 0),
    PB_LAST_FIELD
};

const pb_field_t AuthResponse_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, AuthResponse, state, state, 0),
    PB_LAST_FIELD
};

const pb_field_t NotifyRequest_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, NotifyRequest, current, current, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, NotifyRequest, heatingState, current, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, NotifyRequest, coolingState, heatingState, 0),
    PB_LAST_FIELD
};

const pb_field_t ConfigSet_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, ConfigSet, target, target, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, ConfigSet, gisteris, target, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, ConfigSet, tuningSensor, gisteris, 0),
    PB_LAST_FIELD
};

const pb_field_t ActualConfig_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, ActualConfig, target, target, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, ActualConfig, gisteris, target, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, ActualConfig, tuningSensor, gisteris, 0),
    PB_LAST_FIELD
};

const pb_field_t ConfigChanges_fields[4] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, ConfigChanges, target, target, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, ConfigChanges, gisteris, target, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, ConfigChanges, tuningSensor, gisteris, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(BaseMessage, authRequest) < 65536 && pb_membersize(BaseMessage, authResponse) < 65536 && pb_membersize(BaseMessage, notifyRequest) < 65536 && pb_membersize(BaseMessage, configSet) < 65536 && pb_membersize(BaseMessage, configChanges) < 65536 && pb_membersize(BaseMessage, actualConfig) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_BaseMessage_AuthRequest_AuthResponse_NotifyRequest_ConfigSet_ActualConfig_ConfigChanges)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(BaseMessage, authRequest) < 256 && pb_membersize(BaseMessage, authResponse) < 256 && pb_membersize(BaseMessage, notifyRequest) < 256 && pb_membersize(BaseMessage, configSet) < 256 && pb_membersize(BaseMessage, configChanges) < 256 && pb_membersize(BaseMessage, actualConfig) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_BaseMessage_AuthRequest_AuthResponse_NotifyRequest_ConfigSet_ActualConfig_ConfigChanges)
#endif


/* @@protoc_insertion_point(eof) */
